AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:

  ShankarLambda:
    
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: target/demo-1.0.0.jar
        Handler: com.amazonaws.lambda.demo.LambdaFunctionHandler::handleRequest
        Runtime: java8
        Description: Java function
        MemorySize: 512
        Timeout: 1000
        # Function's execution role
        Policies:
          - AWSLambdaBasicExecutionRole
          - AWSLambdaReadOnlyAccess
          - AWSXrayWriteOnlyAccess
          - AWSLambdaVPCAccessExecutionRole
        Tracing: Active